test_json="""{"log":[
{"user_responses":[
        {"description":"testing
"},
        {"time_categories":[
                {"planning":[
                        {"time_spent":6.000000},
                        {"difficulty":3}
                ]},
                {"coding":[
                        {"time_spent":6.000000},
                        {"difficulty":3}
                ]},
                {"refactoring":[
                        {"time_spent":6.000000},
                        {"difficulty":3}
                ]},
                {"debugging":[
                        {"time_spent":0.000000},
                        {"difficulty":0}
                ]},
                {"optimising":[
                        {"time_spent":6.000000},
                        {"difficulty":5}
                ]}
        ]},     {"tags":[
                {"MPI":false},
                {"OpenMP":true},
                {"Cuda":false},
                {"Kokkos":true},
                {"domain specific work":true}
        ]},
        {"NASA-TLX":[
                {"mental_demand":5},
                {"temporal_demand":3},
                {"performance":6},
                {"effort":4},
                {"frustration":7}
        ]}
]},
{"autogeneratated":[    {"status":""},
        {"files":[
        {"name":"./interfaces/c/fft_join.c","size":3309,"last_modified":1528904996}
        ]},
        {"git_info":[
                {"commit_hash":"a0d20fdf9cd4d9d72c2b2e0cd1ee0749505bca4d"},
                {"branch":"test"}
        ]}
]}
]}"""
