#!/bin/bash

REMOTE_NAME="$1"
REMOTE_LOC="$2"
LOGS_REF=refs/notes/productivity

BREADCRUMB=.bread.crumb

if [ -f ${BREADCRUMB} ]; then
	exit
fi

echo 'done first call' > ${BREADCRUMB}
git push ${REMOTE_NAME} ${LOGS_REF}:${LOGS_REF}
rm ${BREADCRUMB} 
